---
# Playbook to undeploy Ghost and its component
# TO DO
- name: Undeploy Ghost
  hosts: localhost
  roles:
    - { role: undeploy_ghost }
    - { role: undeploy_mysql, when: "delete_data is defined and delete_data == 'true'" }

    